"use client";

import { useState, useEffect } from "react";
import { Download, Loader2, FileX, Trash2 } from "lucide-react";

export default function ReportsHistoryPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/workshop/reports")
      .then(r => r.json())
      .then(res => {
        if (res.success) {
          setReports(res.data);
        }
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const handleDelete = async (id: string) => {
    if (!window.confirm("Are you sure you want to delete this generated report?")) return;
    try {
      const res = await fetch(`/api/workshop/reports/${id}`, { method: 'DELETE' });
      if (res.ok) {
        setReports(reports => reports.filter(r => r.id !== id));
      } else {
        alert("Failed to delete report.");
      }
    } catch (e) {
      alert("Error deleting report.");
    }
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1>Generated Reports</h1>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>History of all exported PowerPoint presentations</p>
        </div>
      </div>

      <div className="card" style={{ padding: 0 }}>
        {loading ? (
          <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem' }}>
            <Loader2 size={32} style={{ animation: 'spin 1s linear infinite', color: 'var(--jspl-blue)' }} />
          </div>
        ) : reports.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '4rem 2rem' }}>
            <FileX size={48} color="var(--text-secondary)" style={{ margin: '0 auto 1rem', opacity: 0.5 }} />
            <h3 style={{ marginBottom: '0.5rem' }}>No reports generated yet</h3>
            <p style={{ color: 'var(--text-secondary)' }}>Generate a new report from the Workshop page.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', minWidth: '600px' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--glass-border)' }}>
                  <th style={{ padding: '1.5rem 1.5rem' }}>Title</th>
                  <th>Status</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th style={{ textAlign: 'right', paddingRight: '1.5rem' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((report) => (
                  <tr key={report.id} style={{ borderBottom: '1px solid var(--glass-border)' }}>
                    <td style={{ padding: '1rem 1.5rem', fontWeight: 'bold' }}>{report.title}</td>
                    <td>
                      <span style={{ 
                        padding: '4px 8px', 
                        borderRadius: '4px', 
                        fontSize: '0.8rem', 
                        fontWeight: 'bold',
                        backgroundColor: report.status === 'Completed' ? '#e8f5e9' : report.status === 'Failed' ? '#ffebee' : '#e3f2fd',
                        color: report.status === 'Completed' ? '#2e7d32' : report.status === 'Failed' ? '#c62828' : '#1565c0'
                      }}>
                        {report.status} {report.status === 'Generating' && `(${report.progress}%)`}
                      </span>
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>{report.createdBy?.name || "System"}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {new Date(report.createdAt).toLocaleString()}
                    </td>
                    <td style={{ textAlign: 'right', paddingRight: '1.5rem', display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', alignItems: 'center' }}>
                      {report.status === 'Completed' && report.fileUrl && (
                        <a 
                          href={report.fileUrl} 
                          download 
                          className="btn btn-primary"
                          style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', fontSize: '0.9rem' }}
                        >
                          <Download size={16} /> Download
                        </a>
                      )}
                      <button 
                        onClick={() => handleDelete(report.id)}
                        style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: '0.5rem', backgroundColor: '#ffebee', color: '#c62828', border: 'none', borderRadius: '4px', cursor: 'pointer', transition: 'background-color 0.2s' }}
                        title="Delete Report"
                        onMouseOver={(e) => e.currentTarget.style.backgroundColor = '#ffcdd2'}
                        onMouseOut={(e) => e.currentTarget.style.backgroundColor = '#ffebee'}
                      >
                        <Trash2 size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
